### ISSUE TITLE
Country for beer() function

### ISSUE THREAD

**Issue by parryc** [alilja/ratebeer#12]
I realized after I made the pull request today, that brewery country had been removed in v2.0.  Is it possible to add it back in, or did you find issues with the way it was derived? 

The necessary code would be (around line 143): 

````
        if ',' in brewery_info[5]:
            # Non-USA addresses
            self.brewery_country = brewery_info[5].split(',')[1].strip()
        else:
            # USA addresses
            self.brewery_country = brewery_info[8].strip()
````

**Comment by alilja** [comment]
I think I removed it because I wanted there to be a clear separation between information about the brewery and the beer, but being that strict in this case seems silly. Makes sense that the beer's country should be available from the beer itself.
