### ISSUE TITLE
Search broken in v2.1

### ISSUE THREAD

**Issue by shamrt** [alilja/ratebeer#15]
RateBeer recently [updated their search page to use bootstrap](http://www.ratebeer.com/findbeer.asp), which has broken `RateBeer.search()`.

Do you have time to fix this? If necessary, I can do so and submit a pull request.

Thanks!

**Comment by OrganicIrradiation** [comment]
I noticed and fixed the search function in this pull request (along with a number of other changes, hopefully improvements): https://github.com/alilja/ratebeer/pull/14

Feel free to try it out and see if there are any issues.

**Comment by shamrt** [comment]
Will do, @OrganicIrradiation. 

@alilja: Assuming the tests pass, is there any hesitation re accepting the PR and updating the PyPI package?

**Comment by alilja** [comment]
Hi @shamrt. Thanks for pointing this out, and thanks to my incredible collaborator @OrganicIrradiation (who's basically written all the code at this point) for hopping on it so quickly.

**Comment by alilja** [comment]
Everything is broken :( I'll take a look at it, but right now search results are reporting nothing.

**Comment by OrganicIrradiation** [comment]
Thanks for the compliments, but I've been using this as a vehicle to tinker and learn more about Python, so I'm just happy to help! Regarding the issues, I just quickly ran the most recent unittests with test.py on my fork (installed using ```pip install git+git://github.com/OrganicIrradiation/ratebeer.git```) and alilja's base (installed using ```pip install git+git://github.com/alilja/ratebeer.git```) and did not have any issues on my end.

However, if I run the unittests on the PyPi version, it has 1 failure and 7 errors, so it looks like the most recent commit needs to be pushed to PyPi (which currently is hosting v2.1).

**Comment by alilja** [comment]
Here are the test errors I get:

    (ratebeer)hellboy:ratebeer andrew$ python test.py
    ............EEEEE
    ======================================================================
    ERROR: test_whitespace_in_url (__main__.TestMisc)
    The rare situation where a URL might have whitespace
    ----------------------------------------------------------------------
    Traceback (most recent call last):
    File "test.py", line 111, in test_whitespace_in_url
      beer = results['beers'][0]
    IndexError: list index out of range

    ======================================================================
    ERROR: test_str_ascii_search (__main__.TestSearch)
    Test out the search function with an ASCII only str search
    ----------------------------------------------------------------------
    Traceback (most recent call last):
    File "test.py", line 125, in test_str_ascii_search
      superset = results['beers'][0].__dict__
    IndexError: list index out of range

    ======================================================================
    ERROR: test_str_nonascii_search (__main__.TestSearch)
    Test out the search function with a str with more than ASCII characters
    ----------------------------------------------------------------------
    Traceback (most recent call last):
    File "test.py", line 135, in test_str_nonascii_search
      superset = results['beers'][0].__dict__
    IndexError: list index out of range

    ======================================================================
    ERROR: test_unicode_ascii_search (__main__.TestSearch)
    Test out the search function with an ASCII only unicode search
    ----------------------------------------------------------------------
    Traceback (most recent call last):
    File "test.py", line 145, in test_unicode_ascii_search
      superset = results['beers'][0].__dict__
    IndexError: list index out of range

    ======================================================================
    ERROR: test_unicode_nonascii_search (__main__.TestSearch)
    Test out the search function with a unicode string with more than ASCII characters
    ----------------------------------------------------------------------
    Traceback (most recent call last):
    File "test.py", line 155, in test_unicode_nonascii_search
      superset = results['beers'][0].__dict__
    IndexError: list index out of range

    ----------------------------------------------------------------------
    Ran 17 tests in 17.378s

    FAILED (errors=5)

**Comment by OrganicIrradiation** [comment]
Just tried it on 2 clean virtualenvs and am having no issues?

    $ mktmpenv --python=/usr/bin/python2
    $ pip install git+git://github.com/alilja/ratebeer.git
    $ wget https://raw.githubusercontent.com/alilja/ratebeer/master/test.py -O test.py
    $ python test.py
    .................
    ----------------------------------------------------------------------
    Ran 17 tests in 22.177s
    
    OK
    $ deactivate
    $ mktmpenv --python=/usr/bin/python3
    $ pip install git+git://github.com/alilja/ratebeer.git
    $ wget https://raw.githubusercontent.com/alilja/ratebeer/master/test.py -O test.py
    $ python test.py
    .................
    ----------------------------------------------------------------------
    Ran 17 tests in 21.065s
    
    OK
    $ deactivate

**Comment by OrganicIrradiation** [comment]
Just wanted to drop another note to see if it would be possible to try out the tests on the github repo and to push the latest branch to PyPI. The latest version online appears to still be 2.1.

**Comment by parryc** [comment]
@OrganicIrradiation It might be that @alilja was on an older version of Requests? As far as I can tell, that's the only dependency difference between v2.0 and v2.1.

What I just did: 
1. Pull master into old environment (Requests 2.6.2)
2. Run tests, get failures from above
3. Run updates on all install packages, Ratebeer v2.1 is installed now, with Requests v2.7.0
4. Run tests, everything is successful

Searching seems to work just fine now (well, after switching to ```beer.name``` instead of ```beer['name']```). Thanks for all the enhancements!

**Comment by alilja** [comment]
Hey guys, it wound up being an older version. Embarrassing. Thanks for all your hard work while I started my new job!
