### ISSUE TITLE
Returns incorrect weighted average for a given beer

### ISSUE THREAD

**Issue by shamrt** [alilja/ratebeer#21]
For example, the following returns a weighted average of `5.0` for Heineken:

    from ratebeer import RateBeer

    rb = RateBeer()
    hs = rb.search('heineken')
    h1 = hs['beers'][0]
    hb = rb.beer(h1.url)
    print hb

The true weighted average, as shown on the website is `2.09`.

**Comment by OrganicIrradiation** [comment]
Thanks for noticing and addressing this!
