### ISSUE TITLE
Failure to fetch beer object

### ISSUE THREAD

**Issue by jtexnl** [alilja/ratebeer#23]
I downloaded the package a week or so ago, and it originally was working beautifully. When I tried it a couple of days ago, it started throwing this error:

```
>>> rb.beer('/beer/new-belgium-tour-de-fall/279122/')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.4/site-packages/ratebeer/ratebeer.py", line 143, in beer
    return self.get_beer(url, True).__dict__
  File "/usr/local/lib/python3.4/site-packages/ratebeer/ratebeer.py", line 139, in get_beer
    return models.Beer(url, fetch)
  File "/usr/local/lib/python3.4/site-packages/ratebeer/models.py", line 72, in __init__
    self._populate()
  File "/usr/local/lib/python3.4/site-packages/ratebeer/models.py", line 134, in _populate
    self.overall_rating = int(soup.find('span', text='overall').next_sibling.next_sibling)
TypeError: int() argument must be a string, a bytes-like object or a number, not 'Tag'
```

I've looked into the code on the lines it's referencing, and can't find anything that should be throwing this error. Any ideas? Other functions (rb.search) seem to be working fine. I tried updating the package, but to no avail.

**Comment by jtexnl** [comment]
I ran the test.py script, and here was its output: 
`.............EEEEE
======================================================================
ERROR: test_whitespace_in_url (__main__.TestMisc)
The rare situation where a URL might have whitespace
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test.py", line 114, in test_whitespace_in_url
    beer = results['beers'][0]
IndexError: list index out of range

======================================================================
ERROR: test_str_ascii_search (__main__.TestSearch)
Test out the search function with an ASCII only str search
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test.py", line 126, in test_str_ascii_search
    beer = results['beers'][0]
IndexError: list index out of range

======================================================================
ERROR: test_str_nonascii_search (__main__.TestSearch)
Test out the search function with a str with more than ASCII characters
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test.py", line 135, in test_str_nonascii_search
    beer = results['beers'][0]
IndexError: list index out of range

======================================================================
ERROR: test_unicode_ascii_search (__main__.TestSearch)
Test out the search function with an ASCII only unicode search
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test.py", line 144, in test_unicode_ascii_search
    beer = results['beers'][0]
IndexError: list index out of range

======================================================================
ERROR: test_unicode_nonascii_search (__main__.TestSearch)
Test out the search function with a unicode string with more than ASCII characters
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test.py", line 153, in test_unicode_nonascii_search
    beer = results['beers'][0]
IndexError: list index out of range

----------------------------------------------------------------------
Ran 18 tests in 21.402s

FAILED (errors=5)
`

**Comment by OrganicIrradiation** [comment]
I just did a quick check and it appears to me that the pypi version (reported as v2.3.1) is out of date.

This completes without errors:

    $ mkvirtualenv testA
    $ workon testA
    $ pip install git+https://github.com/alilja/ratebeer.git
    $ wget https://raw.githubusercontent.com/alilja/ratebeer/master/test.py
    $ python test.py

This does not:

    $ mkvirtualenv testB
    $ workon testB
    $ pip install ratebeer
    $ wget https://raw.githubusercontent.com/alilja/ratebeer/master/test.py
    $ python test.py

@alilja Can you confirm and potentially re-upload the newer version to pipit? (incrementing the version, I believe?)

@jtexnl In the meantime, you should be able to install the newer version using ```pip install git+https://github.com/alilja/ratebeer.git```

**Comment by jtexnl** [comment]
I tried it and it reinstalled, but I'm getting the same problem...

**Comment by alilja** [comment]
The newest version is on PyPi. 

    (ratebeer)hellboy:ratebeer andrew$ python test.py
    ..................
    ----------------------------------------------------------------------
    Ran 18 tests in 24.862s

    OK

**Comment by jtexnl** [comment]
Works now, thanks for the fix!
`>>> rb.beer("/beer/new-belgium-tour-de-fall/279122/")
{'abv': 6.0, 'num_ratings': 260, 'url': '/beer/new-belgium-tour-de-fall/279122/', 'ibu': 38, 'tags': ['cascade', 'amarillo'], 'style_url': '/beerstyles/american-pale-ale/18/', 'name': 'New Belgium Tour de Fall', 'calories': 180, 'seasonal': 'Autumn', 'img_url': 'http://res.cloudinary.com/ratebeer/image/upload/w_120,c_limit/beer_279122.jpg', 'style': 'American Pale Ale', 'brewery': <Brewery('/brewers/new-belgium-brewing-company/77/')>, 'brewed_at': None, 'weighted_avg': 3.34, 'overall_rating': 74, 'style_rating': 71, '_has_fetched': True, 'description': 'New Belgium\x92s love for beer, bikes and benefits is best described by being at Tour de Fat. Our love for Cascade and Amarillo hops is best tasted in our Tour de Fall Pale Ale. We\x92re cruising both across the country during our favorite time of year. Hop on and find Tour de Fall Pale Ale in fall 2014.', 'mean_rating': None}`

**Comment by arfenarf** [comment]
I'm still getting this:  I just downloaded ratebeer.py last week and although I can search, I can't pull a Beer's information.  Can you please point me in the right direction?

`q = rb.beer("/beer/new-belgium-tour-de-fall/279122/")
Traceback (most recent call last):
  File "/Users/kath/anaconda/lib/python2.7/site-packages/IPython/core/interactiveshell.py", line 3066, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-15-1e2d15c8a81d>", line 1, in <module>
    q = rb.beer("/beer/new-belgium-tour-de-fall/279122/")
  File "/Users/kath/anaconda/lib/python2.7/site-packages/ratebeer/ratebeer.py", line 143, in beer
    return self.get_beer(url, True).__dict__
  File "/Users/kath/anaconda/lib/python2.7/site-packages/ratebeer/ratebeer.py", line 139, in get_beer
    return models.Beer(url, fetch)
  File "/Users/kath/anaconda/lib/python2.7/site-packages/ratebeer/models.py", line 72, in __init__
    self._populate()
  File "/Users/kath/anaconda/lib/python2.7/site-packages/ratebeer/models.py", line 134, in _populate
    self.overall_rating = int(soup.find('span', text='overall').next_sibling.next_sibling)
TypeError: int() argument must be a string or a number, not 'Tag'`
