### ISSUE TITLE
Broken beer search

### ISSUE THREAD

**Issue by tumyeto** [alilja/ratebeer#28]
Similar to issue #26, the searching for beers function is also broken.

Running:

import ratebeer
rb = ratebeer.RateBeer()
rb.search('Summit')

Will fail with:

`
File "/usr/lib/python2.7/site-packages/ratebeer/ratebeer.py", line 115, in search
    beer.name = row('td')[0].a.string.strip()
AttributeError: 'NoneType' object has no attribute 'strip'
`

Thanks!

**Comment by OrganicIrradiation** [comment]
Fixed by @OddBloke (thank you!). Merged PR 0000511, which should fix the issue in the github version of the library. Could you please confirm? It's installable using pip with the following command:

    pip install git+git://github.com/alilja/ratebeer.git

**Comment by tumyeto** [comment]
It's working for me now.  Thanks!
