### ISSUE TITLE
Can't grab style list

### ISSUE THREAD

**Issue by Reldey** [alilja/ratebeer#34]
I am getting this error when I try to grab the style list:

>>> rb.beer_style_list()

Traceback (most recent call last):
  File "<pyshell#0>", line 1, in <module>
    rb.beer_style_list()
  File "C:\Python27\lib\site-packages\ratebeer\ratebeer.py", line 159, in beer_style_list
    columns = soup.find_all('table')[2].find_all('td')
IndexError: list index out of range

**Comment by OrganicIrradiation** [comment]
This should be fixed, could you try the HEAD and see if it works for you?

**Comment by OrganicIrradiation** [comment]
It looks like this "fix" breaks the beer_style function, since the beer styles URLs are now in the format of "/top/abbey-dubbel" rather than "/beerstyles/abbey-dubbel/71/", so we can't readily grab the style ID.

**Comment by OrganicIrradiation** [comment]
Ok, now should be fixed. Could you check out pull request 36 and see if it fixes the issue on your end?

**Comment by djordjeandrejevic** [comment]
@OrganicIrradiation 

As I'm not a Python developer, I tested this by replacing original files with models.py and ratebeer.py files. Now I don't get an error like I used to, so thanks for that!

One thing I noticed though is that I don't get valid JSON outputs. It writes occasional `u` letter in front of the value and 

```
{
'seasonal': None,
'num_ratings': 1051,'style': u'India Pale Ale (IPA)', '_has_fetched': True, 'retired': False, 'name': u'BrewDog Punk IPA  (6%)', 'tags': [u'maris otter', u'chinook', u'ahtanum', u'motueka', u'crystal hop'], 'url': '/beer/brewdog-punk-ipa-6/72423/', 'img_url': 'https://res.cloudinary.com/ratebeer/image/upload/w_120,c_limit/beer_72423.jpg', 'mean_rating': None, 'description': u'Re-released as a special in April 2017 \n The recipe was changed at the end of 2009, and this version is no longer made, if you have a bottle with a BBD after 01/01/2012, you should go to the "Punk IPA (5.6%)" version. \n \n \r\nBottle and keg: Filtered. Cask: Unfiltered. \r\nIngredients: Marris Otter Extra Pale Malt; Ahtanum Chinook, Crystal, Motueka hops. IBUs 60 \r\n\r\nA beer of inherent contradiction. This heavy weight of the beer world is strikingly delicate with a white gold appearance. The light fruity aroma dominates the initial confrontation; lychee, kiwi and passionfruit all prevail with subtle nuances of cherry and strawberry. Don\'t be fooled however by this smooth medium bodied ale. As it trickles down your throat as this wolf in sheep\'s clothing begins to grow teeth. The bite comes as the bitterness builds and endures no matter how hard the malty sweetness of the alcohol tries to tame this ferocious beast.', 'calories': 180, 'ibu': 60, 'brewed_at': None, 'abv': 6.0, 'style_rating': 70, 'style_url': '/beerstyles/india-pale-ale-ipa/17/', 'brewery': <Brewery('/brewers/brewdog/8534/')>, 'weighted_avg': 3.46, 'overall_rating': 84}

**Comment by OrganicIrradiation** [comment]
Glad to hear it's fixed! The "u" indicates that field is a unicode string (I'm assuming you are running Python 2?). One possibility for your JSON formatting issue could be to use the built-in ```json``` library:

```python
import json
from ratebeer import RateBeer

b = RateBeer().get_beer('/beer/deschutes-altitude-amber/92102/')._populate()
b.brewery = b.brewery.url
print json.dumps(b.__dict__)
```

Note that I am replacing the brewery attribute (which is normally a non-serializable Brewery object) with the url.

**Comment by djordjeandrejevic** [comment]
@OrganicIrradiation 

This worked, thank you so much. Do you know how can I change character encoding, I would love to avoid those special characters and have regular latin ones (e.g. `\u0107` should be `ć`, `\u009e` should be `ž` and so on). Tried so many things in Python, even in Node.js (after exporting JSON using a Python script) but no luck. Thanks!

**Comment by OrganicIrradiation** [comment]
Character encoding is a PITA and in Python 2 it is a real PITA, which is why I prefer Python 3, where all strings are Unicode. When you're asking how to change character encoding, is the issue when you dump to JSON? If so, this might be relevant: https://stackoverflow.com/questions/18337407/saving-utf-8-texts-in-json-dumps-as-utf8-not-as-u-escape-sequence

I can't really make a recommendation other than Googling.
