### ISSUE TITLE
Empty Results

### ISSUE THREAD

**Issue by rohan-thakur** [alilja/ratebeer#40]
Hi,

I pip installed ratebeer (tried on both Python 2.7 and 3.4), and am getting empty results when running the sample query. Is there a step I've missed in setup? Please let me know if you guys have any insight. Thanks!

<img width="600" alt="screen shot 2017-06-08 at 2 17 08 pm" src="https://user-images.githubusercontent.com/13525999/26943932-3b2dd8a2-4c55-11e7-99fa-a9950b28c0b8.png">

**Comment by rohan-thakur** [comment]
When I try to look for a specific beer page:

<img width="582" alt="screen shot 2017-06-08 at 2 21 18 pm" src="https://user-images.githubusercontent.com/13525999/26944198-f887889e-4c55-11e7-9038-ce28bfe88d41.png">

**Comment by parryc** [comment]
Hi @rohan-thakur, please try downloading the package directly from github, rather than relying on the pip version.

**Comment by rohan-thakur** [comment]
Awesome, that worked. Thanks.
