### ISSUE TITLE
get_reviews throwing an error

### ISSUE THREAD

**Issue by pipbutters** [alilja/ratebeer#41]
When trying to iterate through reviews getting AttributeError.

> for r in rev:
 ...\site-packages\ratebeer\models.py", line 235, in get_reviews
    yield Review(review_soup)
  ...\site-packages\ratebeer\models.py", line 261, in __init__
    raw_ratings = zip(*[iter(review_soup.find('strong').find_all(["big", "small"]))] * 2)
AttributeError: 'NoneType' object has no attribute 'find_all' `

Was working a couple of weeks ago.
Any insight how this can be fixed?

Thanks

**Comment by parryc** [comment]
@pipbutters looks like support for raw ratings (appearance, taste, etc.) has been removed from Ratebeer. You can delete the lines [260 to 269](https://github.com/parryc/ratebeer/commit/839d3574dcb0004ccbf08bae242c5646a8a3eec3) in the models.py file to return the Review object back to working condition.

**Comment by pipbutters** [comment]
Works a treat.
Thanks!

**Comment by OrganicIrradiation** [comment]
The information is still there, just hidden in the div's title attribute. Inspecting a review's rating shows (for example from https://www.ratebeer.com/beer/russian-river-pliny-the-elder/8936/):

  > ```<div style="display:inline; padding: 0px 0px; font-size: 24px; font-weight: bold; color: #036;" title="4.1 out of 5.0<br /><small>Aroma 8/10<br />Appearance 4/5<br />Taste 8/10<br />Palate 4/5<br />Overall 17/20<br /></small>">4.1</div>```

Should be a pretty simple fix.

**Comment by OrganicIrradiation** [comment]
Fixed by PR #42
