### ISSUE TITLE
Encoding appears to have issues

### ISSUE THREAD

**Issue by parryc** [alilja/ratebeer#43]
It appears some point in the past few weeks (July 2017), the encodings for unicode data coming from RateBeer got all messed up.  There are two tests `test_beer_unicode` and `test_beer` which are failing because of it. 

`test_beer` fails because the copy has switched back from using `'` to using `’`, which can have erroneous encodings. 
`test_beer_unicode` fails because the beer name comes through as `SteÃ°ji OktÃ³berbjÃ³r`.  

Both appear to be due to BS4 thinking the encodings are _iso-8859-1_, but the raw source of the page is being displayed as unicode, and the charset in the <meta> tags says utf-8 as well.  Not sure what's up.

**Comment by parryc** [comment]
Upgrade Requests appears to fix the fact that the textual output was weird ([seems they fixed a bug somewhere](http://docs.python-requests.org/en/master/community/updates/?highlight=unicode#id19)), so now it's clear that there is an encoding issue, when looking at the raw requests output.

**Comment by parryc** [comment]
Ahaha, omg, it's worse than I thought:

```python
s = u'SteÃ°ji OktÃ³berbjÃ³r'
print(s.encode('utf-16le').decode('utf-16le').encode('latin-1'))
# Steðji Októberbjór
```

Ran out of time tonight, but I'll take another crack at trying to figure out what's up with this encoding later this week. A possible solution is to wrap all setting of text with a function that checks if the string is all ASCII, and if not, does the crazy encoding and decoding necessary to get it readable.

**Comment by OrganicIrradiation** [comment]
@parryc, can you try out the proposed fix?

**Comment by parryc** [comment]
@OrganicIrradiation works like a charm. What a subtle thing. Major props for figuring that out! I think I spent too much time thinking it was a problem with BeautifulSoup...smh.

**Comment by OrganicIrradiation** [comment]
I really despise dealing with encodings, so hopefully this is an appropriate fix.
